<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>CustomWFUI.Showcase</RootNamespace>
    <AssemblyName>CustomWFUI.Showcase</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomWFUI\CustomWFUI.csproj" />
  </ItemGroup>

</Project>
